### ISSUE TITLE
Replace fzf with skim

### ISSUE THREAD

**Issue by adamrodger** [adamrodger/gcloud-ctx#17]
Replace `fzf` external tool usage with `skim`: https://github.com/lotabout/skim

This has the advantages:

- The user won't have to add any third party tools to get fuzzy matching
- We can control how the display looks instead of showing direct output of other commands

**Comment by c3st7n** [comment]
Didn't realise you had self-assigned this, but just raised a PR  #18  which seems to work for replacing with skim (docs are somewhat lacking on skim as a lib).

**Comment by adamrodger** [comment]
No problems, gratefully received!
